tcpdump tool: option to capture for specified duration
Add `--duration` option to auto terminate tcpdump after a specified
period of  time.

Fixes: #14

Signed-off-by: Sunil Thaha <sthaha@redhat.com>

diff --git a/tcpdump/oc-tools-tcpdump b/tcpdump/oc-tools-tcpdump
--- a/tcpdump/oc-tools-tcpdump
+++ b/tcpdump/oc-tools-tcpdump
@@ -308,7 +308,9 @@ Usage:
   $app -h|--help
 
 Options:
-  --no-nodes: Do not capture the traffic from nodes
+  --no-nodes          : Do not capture the traffic from nodes
+  --duration DURATION : Capture only of certain DURATION.
+                        E.g. 10, 10s, 5m, 3h
 
 Examples:
 
@@ -322,6 +324,9 @@ Examples:
   # but do not capture node traffic
   $app --no-nodes -n web -l app=nginx
 
+  # Capture pod traffic for only 10 seconds
+  $app --no-nodes --duration 10s -n web -l app=nginx
+
 EOF_HELP
 
   echo -e "$help"
@@ -331,6 +336,8 @@ EOF_HELP
 
 declare  SHOW_USAGE=false
 declare  CAPTURE_NODE_PACKETS=true
+declare  AUTO_KILL=false
+declare  AUTO_KILL_DURATION=0
 
 declare -a POD_ARGS=()
 parse_args() {
@@ -344,18 +351,35 @@ parse_args() {
     case $1 in
     -h|--help)    SHOW_USAGE=true; return ;; # exit the loop
     --no-nodes)   CAPTURE_NODE_PACKETS=false; shift ;;
+    --duration)
+      AUTO_KILL=true;
+      AUTO_KILL_DURATION="$2"
+      shift 2 ;;
     *)   POD_ARGS+=( "$1" ); shift
     esac
   done
   return 0
 }
 
+validate_duration() {
+  local x="$1"; shift
+  echo "$x" | grep -E '\d+'
+  [[ $x =~ ^[0-9]+\.?[0-9]*[smh]?$ ]]
+}
+
+validate() {
+  $AUTO_KILL && validate_duration "$AUTO_KILL_DURATION" || {
+    err "Invalid duration $AUTO_KILL_DURATION"
+    return 1
+  }
+  return 0
+}
 
 
 main() {
-  ## usage
   parse_args "$@" || usage
   $SHOW_USAGE && usage 0
+  validate || usage 1
 
 
   info "Finding pods matching \"${POD_ARGS[@]}\""
@@ -383,11 +407,23 @@ main() {
   start_tcpdump_all_nodes $CAPTURE_NODE_PACKETS
 
   ### sleep is propotional to the number of pods started
-  sleep $( bc <<< "3 + ${#PODS[@]} * 0.5" )
+  sleep $( bc <<< "3 + ${#PODS[@]} * 0.3" )
+
   h2 tcpdump of all pods have started. Press Ctrl+C to stop
   info All pcap files will be copied to $LOCAL_PCAP_DIR
 
-  sleep infinity
+  if $AUTO_KILL ; then
+    info "Capture will auto terminate after $AUTO_KILL_DURATION"
+    sleep "$AUTO_KILL_DURATION"
+    # don't kill if already in cleanup; e.g user may have killed the process
+    $CLEANUP_IN_PROGRESS || {
+      info "Terminating script after $AUTO_KILL_DURATION"
+      kill -INT $$
+    }
+  else
+    sleep infinity
+  fi
+
   return $?
 }
 
